/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.VendaDAO;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.ModBaixaParcela;
import model.ModVenda;
import util.ModHeader;
import util.ModRowEstado;
import util.Util;

/**
 *
 * @author ALEX PC
 */
public class frmParcelasBaixa extends javax.swing.JFrame {
    
    Util utilidades = new Util();
    ModBaixaParcela modeloBaixaParcela;
    ModVenda modeloVenda;
    VendaDAO repositorio;
    
    DefaultTableModel modelo;
    
    String id_parcela = "";
    String data_venc;
    String valor_parc;
    
    
    boolean verificador_de_click = false;

    public frmParcelasBaixa() {
        initComponents();
        modeloBaixaParcela = new ModBaixaParcela();
        repositorio =  new VendaDAO();
        this.txtIdParcela.setEnabled(false);
        ajustarTabelaBaixaParcelas();
        if (verificaParcelasPagas()==true) {
            tabelaBaixaParcelas.setEnabled(false);
            tabelaBaixaParcelas.setComponentPopupMenu(new JPopupMenu());
        }
    }
    
    public frmParcelasBaixa(ModVenda modeloVenda){
        initComponents();
        this.modeloVenda = modeloVenda;
        modeloBaixaParcela = new ModBaixaParcela();
        repositorio =  new VendaDAO();
        this.txtIdParcela.setEnabled(false);
        ajustarTabelaBaixaParcelas();
        verNotaMenu(modeloVenda.getId_venda());
        if (verificaParcelasPagas()==true) {
            tabelaBaixaParcelas.setEnabled(false);
            tabelaBaixaParcelas.setComponentPopupMenu(new JPopupMenu());
        }
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopupParcela = new javax.swing.JPopupMenu();
        menuVerComprovante = new javax.swing.JMenuItem();
        menuPagarParcela = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        txtIdParcela = new javax.swing.JTextField();
        txtDataVencParcelas = new javax.swing.JTextField();
        jLabel82 = new javax.swing.JLabel();
        txtId_venda = new javax.swing.JTextField();
        btnVerNota = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtValorParcela = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaBaixaParcelas = new javax.swing.JTable();

        PopupParcela.setBackground(new java.awt.Color(255, 255, 255));
        PopupParcela.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        PopupParcela.setForeground(new java.awt.Color(0, 34, 57));
        PopupParcela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PopupParcela.setLabel("");
        PopupParcela.setOpaque(false);
        PopupParcela.setPreferredSize(new java.awt.Dimension(180, 80));

        menuVerComprovante.setBackground(new java.awt.Color(204, 204, 204));
        menuVerComprovante.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        menuVerComprovante.setForeground(new java.awt.Color(0, 34, 57));
        menuVerComprovante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/verNota.png"))); // NOI18N
        menuVerComprovante.setText("Ver Comprovante");
        menuVerComprovante.setBorder(null);
        menuVerComprovante.setIconTextGap(10);
        menuVerComprovante.setMargin(new java.awt.Insets(0, 20, 0, 0));
        menuVerComprovante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerComprovanteActionPerformed(evt);
            }
        });
        PopupParcela.add(menuVerComprovante);

        menuPagarParcela.setBackground(new java.awt.Color(204, 204, 204));
        menuPagarParcela.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        menuPagarParcela.setForeground(new java.awt.Color(0, 34, 57));
        menuPagarParcela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/talao-de-cheques.png"))); // NOI18N
        menuPagarParcela.setText("Pagar ");
        menuPagarParcela.setBorder(null);
        menuPagarParcela.setIconTextGap(10);
        menuPagarParcela.setMargin(new java.awt.Insets(0, 20, 0, 0));
        menuPagarParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPagarParcelaActionPerformed(evt);
            }
        });
        PopupParcela.add(menuPagarParcela);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario Baixas");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 34, 57));

        jPanel45.setBackground(java.awt.Color.lightGray);
        jPanel45.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dar baixar parcelas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(0, 34, 57))); // NOI18N
        jPanel45.setForeground(new java.awt.Color(0, 34, 57));

        jLabel77.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(0, 34, 57));
        jLabel77.setText("Cod. Parcela.");

        jLabel78.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(0, 34, 57));
        jLabel78.setText("Descontar Parcela.");

        jLabel79.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(0, 34, 57));
        jLabel79.setText("Data Venc.");

        txtIdParcela.setBackground(new java.awt.Color(255, 255, 255));
        txtIdParcela.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtIdParcela.setForeground(new java.awt.Color(0, 34, 57));
        txtIdParcela.setDisabledTextColor(new java.awt.Color(0, 34, 57));
        txtIdParcela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdParcelaKeyPressed(evt);
            }
        });

        txtDataVencParcelas.setBackground(new java.awt.Color(255, 255, 255));
        txtDataVencParcelas.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtDataVencParcelas.setForeground(new java.awt.Color(0, 34, 57));

        jLabel82.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(0, 34, 57));
        jLabel82.setText("Nro. Nota.");

        txtId_venda.setBackground(new java.awt.Color(255, 255, 255));
        txtId_venda.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtId_venda.setForeground(new java.awt.Color(0, 34, 57));
        txtId_venda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtId_vendaKeyPressed(evt);
            }
        });

        btnVerNota.setBackground(new java.awt.Color(0, 34, 57));
        btnVerNota.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnVerNota.setForeground(new java.awt.Color(255, 255, 255));
        btnVerNota.setText("Ver Nota");
        btnVerNota.setBorder(null);
        btnVerNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerNotaActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 34, 57));
        btnCancelar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtValorParcela.setBackground(new java.awt.Color(255, 255, 255));
        txtValorParcela.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtValorParcela.setForeground(new java.awt.Color(0, 34, 57));
        txtValorParcela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorParcelaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel45Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtId_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDataVencParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel82))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel78)
                    .addComponent(txtIdParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerNota, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel45Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel45Layout.createSequentialGroup()
                        .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel45Layout.createSequentialGroup()
                        .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel45Layout.createSequentialGroup()
                                .addComponent(txtId_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDataVencParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel45Layout.createSequentialGroup()
                                .addComponent(btnVerNota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        tabelaBaixaParcelas.setBackground(new java.awt.Color(255, 255, 255));
        tabelaBaixaParcelas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabelaBaixaParcelas.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tabelaBaixaParcelas.setForeground(new java.awt.Color(0, 34, 57));
        tabelaBaixaParcelas.getTableHeader().setFont(new Font("Arial", Font.BOLD, 12));
        tabelaBaixaParcelas.getTableHeader().setOpaque(false);
        tabelaBaixaParcelas.getTableHeader().setBackground(new Color(0,34,57));
        tabelaBaixaParcelas.getTableHeader().setForeground(new Color(255,255,255));
        tabelaBaixaParcelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Parcela.", "Nro. Nota.", "Valor Parc.", "Data Venc.", "Estado."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaBaixaParcelas.setComponentPopupMenu(PopupParcela);
        tabelaBaixaParcelas.setFocusable(false);
        tabelaBaixaParcelas.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelaBaixaParcelas.setOpaque(false);
        tabelaBaixaParcelas.setRowHeight(25);
        tabelaBaixaParcelas.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tabelaBaixaParcelas.setSelectionForeground(new java.awt.Color(0, 34, 57));
        tabelaBaixaParcelas.setShowVerticalLines(false);
        tabelaBaixaParcelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaBaixaParcelasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaBaixaParcelas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtIdParcelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdParcelaKeyPressed

    }//GEN-LAST:event_txtIdParcelaKeyPressed

    private void btnVerNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerNotaActionPerformed
        repositorio.gerarNota(Integer.parseInt(txtId_venda.getText()));    
    }//GEN-LAST:event_btnVerNotaActionPerformed

    private void txtId_vendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtId_vendaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            int id_venda = Integer.parseInt(txtId_venda.getText());
            modeloBaixaParcela.setId_venda(id_venda);
            modeloBaixaParcela = repositorio.buscarParcelas(id_venda);
            this.txtIdParcela.setText(String.valueOf(modeloBaixaParcela.getId_parcela()));
            this.txtId_venda.setText(String.valueOf(modeloBaixaParcela.getId_venda()));
            this.txtDataVencParcelas.setText(modeloBaixaParcela.getData_venc());
            this.txtValorParcela.setText(utilidades.formatoPrecio(modeloBaixaParcela.getValor_parcela()));
            limparTabelaBaixaParcelas();
            preecherTabela(Integer.parseInt(txtId_venda.getText()));
            this.txtId_venda.setText(returnNro_factura(id_venda));
            this.txtValorParcela.requestFocus();
            if(verificaParcelasPagas() == false){
                tabelaBaixaParcelas.setEnabled(true);
                tabelaBaixaParcelas.setComponentPopupMenu(PopupParcela);
            }
        }
    }//GEN-LAST:event_txtId_vendaKeyPressed

    private void tabelaBaixaParcelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaBaixaParcelasMouseClicked
        id_parcela = tabelaBaixaParcelas.getValueAt(tabelaBaixaParcelas.getSelectedRow(), 0).toString();
        data_venc = tabelaBaixaParcelas.getValueAt(tabelaBaixaParcelas.getSelectedRow(), 3).toString();
        valor_parc = tabelaBaixaParcelas.getValueAt(tabelaBaixaParcelas.getSelectedRow(), 2).toString();
        txtIdParcela.setText(id_parcela);
        txtValorParcela.setText(valor_parc);
        txtDataVencParcelas.setText(data_venc);
    }//GEN-LAST:event_tabelaBaixaParcelasMouseClicked

    private void txtValorParcelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorParcelaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            float novo_valor = utilidades.convertirFloat(txtValorParcela.getText());
            txtValorParcela.setText(utilidades.formatoCosto(novo_valor));
            if (id_parcela.equals("")) {
                JOptionPane.showMessageDialog(null, "Selecione Parcela");
            }else{
                float valor_atual = utilidades.convertirFloat(tabelaBaixaParcelas.getValueAt(tabelaBaixaParcelas.getSelectedRow(), 2).toString());
                float valor = valor_atual - novo_valor;
                if (valor < 0) {
                    JOptionPane.showMessageDialog(null, "Valor exede ao valor da parcela");
                    txtValorParcela.setText("");
                }else if(valor == 0){
                    int id_vend = Integer.parseInt(txtId_venda.getText());
                    int id_parcela = Integer.parseInt(txtIdParcela.getText());
                    repositorio.darBaixaParcela(id_parcela);
                    limparTabelaBaixaParcelas();
                    preecherTabela(id_vend);
                    if(verificaParcelasPagas() == true){
                        repositorio.atualizarEstadoVenda(id_vend,"Finalizado");
                        repositorio.gerarNota(id_vend);
                        ajustarTabelaBaixaParcelas();
                    }
                    limparTabelaBaixaParcelas();
                    preecherTabela(id_vend);
                }else{
                    repositorio.atualizarValorParcela(Integer.parseInt(txtIdParcela.getText()),valor_atual - novo_valor);
                    limparTabelaBaixaParcelas();
                    preecherTabela(Integer.parseInt(txtId_venda.getText()));
                    txtValorParcela.setText(utilidades.formatoCosto(valor_atual - novo_valor));
                }
            }
        }
    }//GEN-LAST:event_txtValorParcelaKeyPressed

    private void menuVerComprovanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerComprovanteActionPerformed
        if (tabelaBaixaParcelas.getValueAt(tabelaBaixaParcelas.getSelectedRow(), 4).equals("Pendente")) {
            JOptionPane.showMessageDialog(null, "Nenhum comprovante encontrado!");
        }else{
            verComprovanteParcela();
        }
    }//GEN-LAST:event_menuVerComprovanteActionPerformed

    private void menuPagarParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPagarParcelaActionPerformed
        if (txtId_venda.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o Nro. da Venda!");
        }else{
            int id_vend = Integer.parseInt(txtId_venda.getText());
            int id_parcela = Integer.parseInt(txtIdParcela.getText());
            repositorio.darBaixaParcela(id_parcela);
            limparTabelaBaixaParcelas();
            preecherTabela(id_vend);
            if(verificaParcelasPagas() == true){
                repositorio.atualizarEstadoVenda(id_vend,"Finalizado");
                repositorio.gerarNota(id_vend);
                ajustarTabelaBaixaParcelas();
            }
            limparTabelaBaixaParcelas();
            preecherTabela(id_vend);    
        }
    }//GEN-LAST:event_menuPagarParcelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmParcelasBaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmParcelasBaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmParcelasBaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmParcelasBaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmParcelasBaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu PopupParcela;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnVerNota;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JMenuItem menuPagarParcela;
    public javax.swing.JMenuItem menuVerComprovante;
    public javax.swing.JTable tabelaBaixaParcelas;
    public javax.swing.JTextField txtDataVencParcelas;
    public javax.swing.JTextField txtIdParcela;
    public javax.swing.JTextField txtId_venda;
    public javax.swing.JTextField txtValorParcela;
    // End of variables declaration//GEN-END:variables
    
    private void preecherTabela(int id_venda){
        
        ArrayList<ModBaixaParcela> list = repositorio.listarVendaParcelas(id_venda);
        
        Object[] objeto = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            objeto[0] = returnID(list.get(i).getId_parcela());
            objeto[1] = returnNro_factura(list.get(i).getId_venda());
            objeto[2] = utilidades.formatoPrecio(list.get(i).getValor_parcela());
            objeto[3] = list.get(i).getData_venc();
            objeto[4] = list.get(i).getEstado();
            modelo.addRow(objeto);
        }
        tabelaBaixaParcelas.setModel(modelo);
    }
    
    private void limparTabelaBaixaParcelas(){
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i-1;
        }
    }
    
    private void ajustarTabelaBaixaParcelas(){
        
        modelo = (DefaultTableModel) tabelaBaixaParcelas.getModel();
        //Insere o header na tabelaBaixaParcelas
        JTableHeader header = tabelaBaixaParcelas.getTableHeader();
        header.setDefaultRenderer(new ModHeader());
        tabelaBaixaParcelas.setTableHeader(header);
        
        DefaultTableCellRenderer boxCentro = new DefaultTableCellRenderer();
        DefaultTableCellRenderer boxDireita = new DefaultTableCellRenderer();
        ModRowEstado boxEstado = new ModRowEstado();
        boxDireita.setHorizontalAlignment(SwingConstants.RIGHT);
        boxCentro.setHorizontalAlignment(SwingConstants.CENTER);
        
        tabelaBaixaParcelas.getColumn(tabelaBaixaParcelas.getColumnName(0)).setCellRenderer(boxCentro);
        tabelaBaixaParcelas.getColumn(tabelaBaixaParcelas.getColumnName(1)).setCellRenderer(boxCentro);
        tabelaBaixaParcelas.getColumn(tabelaBaixaParcelas.getColumnName(3)).setCellRenderer(boxCentro);
        tabelaBaixaParcelas.getColumn(tabelaBaixaParcelas.getColumnName(4)).setCellRenderer(boxEstado);
        tabelaBaixaParcelas.getColumn(tabelaBaixaParcelas.getColumnName(2)).setCellRenderer(boxDireita);
    }
    
    private boolean verificaParcelasPagas(){
        String estado_string;
        for (int i = 0; i < tabelaBaixaParcelas.getRowCount(); i++) {
            estado_string = tabelaBaixaParcelas.getValueAt(i, 4).toString();
            if(estado_string.equals("Pendente")){
                return false;
            }
        }
        return true;
    }
    
    
    private void verNotaMenu(int id_venda){
        modeloBaixaParcela.setId_venda(id_venda);
        modeloBaixaParcela = repositorio.buscarParcelas(id_venda);
        this.txtIdParcela.setText(String.valueOf(modeloBaixaParcela.getId_parcela()));
        this.txtId_venda.setText(String.valueOf(modeloBaixaParcela.getId_venda()));
        this.txtDataVencParcelas.setText(modeloBaixaParcela.getData_venc());
        this.txtValorParcela.setText(utilidades.formatoPrecio(modeloBaixaParcela.getValor_parcela()));
        limparTabelaBaixaParcelas();
        preecherTabela(Integer.parseInt(txtId_venda.getText()));
        this.txtId_venda.setText(returnNro_factura(id_venda));
        this.txtValorParcela.requestFocus();
    }
    
    private void verComprovanteParcela(){
        String id_parcela = tabelaBaixaParcelas.getValueAt(tabelaBaixaParcelas.getSelectedRow(), 0).toString();
        String nro_factura = txtId_venda.getText();
        repositorio.gerarComprovante(Integer.parseInt(id_parcela), nro_factura);
    }
    
    private String returnNro_factura(int number){
        String numero = "";
        int length = String.valueOf(number).length();
        if(length == 1){
                numero = "0000"+number;
        }
        if(length == 2){
                numero = "000"+number;
        }
        if(length == 3){
                numero = "00"+number;
        }
        if(length == 4){
                numero = "0"+number;
        }
        if(length == 5){
                numero = ""+number;
        }
        return numero;
    }
    
    private String returnID(int number){
        String numero = ""+number;
        int length = String.valueOf(number).length();
        if(length == 1){
                numero = "0"+number;
        }
        if(length == 2){
                numero = ""+number;
        }
        
        return numero;
    }
}
